name: Test & Lint all

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-java:
    name: Java
    runs-on: ubuntu-latest
    env:
      working-directory: ./java
    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: mvn spotbugs:check

      - name: Test
        working-directory: ${{env.working-directory}}
        run: mvn test

  test-go:
    name: Go
    runs-on: ubuntu-latest
    env:
      working-directory: ./go
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Get dependencies
        run: go get .

      - name: Install golangci-lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: $(go env GOPATH)/bin/golangci-lint run ./...

      - name: Tests
        working-directory: ${{env.working-directory}}
        run: make test

  test-python:
    name: Python 3.11
    runs-on: ubuntu-latest
    env:
      working-directory: ./python

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Lint (flake8)
        working-directory: ${{env.working-directory}}
        run: |
          make lint

      - name: Type hints (mypy)
        working-directory: ${{env.working-directory}}
        run: |
          make type-hint

      - name: Test (pytest)
        working-directory: ${{env.working-directory}}
        run: |
          make test

  test-kotlin:
    name: Kotlin
    runs-on: ubuntu-latest
    env:
      working-directory: ./kotlin

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Lint (ktlint)
        working-directory: ${{env.working-directory}}
        run: ./gradlew ktlintCheck

      - name: Test (JUnit 5)
        working-directory: ${{env.working-directory}}
        run: ./gradlew test

  test-rust:
    name: Rust
    runs-on: ubuntu-latest
    env:
      working-directory: ./rust
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Lint (clippy)
        working-directory: ${{env.working-directory}}
        run: make lint

      - name: Test
        working-directory: ${{env.working-directory}}
        run: make test
